### ISSUE TITLE
Guava postfix toImmutableList does not work

### ISSUE THREAD

**Issue by m-titov** [xylo/intellij-postfix-templates#102]
## collection conversions ##

.toImmutableList : convert to Immutable List
	ARRAY                    →  ImmutableList.copyOf($expr$)
	java.util.Collection     →  ImmutableList.copyOf($expr$)
	java.lang.Iterable       →  ImmutableList.copyOf($expr$)
	java.util.stream.Stream  →  $expr$.collect(ImmutableList.toImmutableList())

.toImmutableSet : convert to Immutable Set
	ARRAY                    →  ImmutableSet.copyOf($expr$)
	java.util.Collection     →  ImmutableSet.copyOf($expr$)
	java.lang.Iterable       →  ImmutableSet.copyOf($expr$)
	java.util.stream.Stream  →  $expr$.collect(ImmutableSet.toImmutableSet())

.toImmutableMap : convert to Immutable Map
	ARRAY                    →  Arrays.stream($expr$).collect(ImmutableMap.toImmutableMap($keyF$, $valueF$))
	java.util.Collection     →  $expr$.stream().collect(ImmutableMap.toImmutableMap($keyF$, $valueF$))
	java.lang.Iterable       →  StreamSupport.stream($expr$.spliterator(), false).collect(ImmutableMap.toImmutableMap($keyF$, $valueF$))
	java.util.stream.Stream  →  $expr$.collect(ImmutableMap.toImmutableMap($keyF$, $valueF$))

such postfix doesn't work 
![image](https://user-images.githubusercontent.com/25036750/54478990-33b2fe80-4821-11e9-8ab4-5f50a201de6a.png)

**Comment by xylo** [comment]
I just put your templates into a template file and it works in my case:
![grafik](https://user-images.githubusercontent.com/577869/54479870-0450c180-4822-11e9-81a8-3dcbd15892cb.png)

**Comment by xylo** [comment]
Ah, now I see what's the problem.  You made a line break before you typed `.toI`.  I this case IDEA does not consider your code as template name anymore.

**Comment by m-titov** [comment]
sad
