### ISSUE TITLE
Update to Intellij Idea 191 

### ISSUE THREAD

**Issue by goodwinnk** [xylo/intellij-postfix-templates#104]
Current version of plugin is incompatible with 191 because of API change in bundled Kotlin plugin. File `CustomKotlinStringPostfixTemplate` is affected because of `FLOAT_CONSTANT`, `INTEGER_CONSTANT` and `CHARACTER_CONSTANT` usages (http://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2019.html)

I'm sorry for this trouble but this change was needed for implementing a better indexing for PSI element in Kotlin. It's now too late to fix this compatibility issue because it has been already released in `1.3.21` Kotlin version.

No changes in code are needed but recompilation and version updates are required to fix runtime errors. 

I see two ways for fixing the issue. One is to update dependencies to 191 version and continue development only for it, the second one is calling changes fields with reflection. There's a tedious third way with supporting two versions of plugin, but I think it's not needed right now.

I have prepared an update if you going to proceed with the first option:
https://github.com/xylo/intellij-postfix-templates/pull/103

**Comment by xylo** [comment]
Thanks a lot for this info and the patch.  I will go for the first solution and will just backport all changes to the 2018.2 branch.
