### ISSUE TITLE
Doesn't work with non-empty string literals in PHP

### ISSUE THREAD

**Issue by alozytskyi** [xylo/intellij-postfix-templates#113]
Neither `ANY` or `string` are working

```php
<?php

"test".len<TAB>
```

expected: 

```php
<?php

strlen("test");
```

What do I get:

The autocompletion does not contain any suggestion from `xylo.string` or custom template,  `<TAB>` does not expand it to intended template

**Comment by alozytskyi** [comment]
UPD: seems to be working as expected when string is empty, e.g. "".len tries to expand to either array version(incorrect) or to strlen version(correct)

**Comment by xylo** [comment]
Thanks for the report.  That's indeed strange.

**Comment by xylo** [comment]
Fixed in version 2.10.1.
