### ISSUE TITLE
Open IDEA Preferences hang on

### ISSUE THREAD

**Issue by Arthur-Chan** [xylo/intellij-postfix-templates#117]
This plugin is excellent。
But
When I open the Preferences of Intellij,
then select the `Custom Postfix Templates` tab,
it will hang on a few minutes and nothing to show.
I don't know why. 
Versions below: 

IDEA Version: 2019.1
OS : macOS Mojave 10.14.4

Please help and check it.
Thanks!!!

**Comment by xylo** [comment]
Hm, interesting... Thanks for the report.

**Comment by Arthur-Chan** [comment]
Thanks for your replay.
Today I modify the IDEA vm options

before
> -Xms128
   -Xmx1500m

after
> -Xms512m
   -Xmx2048m

Then It works.
I confused.

I tried this on my other windows computer,
and vm options I never change,  it uses the IDEA default options below
> -Xms128m
   -Xmx512m

It also works and never hang on.

Hope the situation will be helpful.
Thanks!

**Comment by xylo** [comment]
Oh, yes.  That's a good info for reproduction I guess.

**Comment by xylo** [comment]
Hm, I tried different things (changed the memory settings of IDEA, simulated slow internet connections, increased the CPU load of IDEA via indexing, PSI parsing), but I could not reproduce the bug.  However, I know that I also had this problem once (long ago).  But currently I don't know what to do next. :(

**Comment by Arthur-Chan** [comment]
I could not reproduce this bug either.
However, Now IDEA works well.Let's forget about it.
😁😁😁

**Comment by xylo** [comment]
OK. 🙂
