### ISSUE TITLE
Chains of postfix completions in PyCharm

### ISSUE THREAD

**Issue by sekwiatkowski** [xylo/intellij-postfix-templates#118]
Thanks so much for your work! This is one of the most useful plugins I've been using over the years.

Quick question regarding chains of postfix completions in Python applied to lists. I have a list named `targets` and the following two custom templates:

```
.set: set
	ANY →  set($expr$)

.asc: sorted
	ANY →  sorted($expr$)
```

`targets.set` expands to `set(targets)` as expected, but postfix completion does not work at all for `set(targets).asc`. Do I have to change the scripts some way to be able to apply the completion to the set?

Incidentally, the built-in `len` template works in this context: `set(targets).len` expands to `len(set(targets))`.

**Comment by xylo** [comment]
Fixed in Version 2.9.2.  Thanks for the report.

**Comment by xylo** [comment]
Version 2.10.0 supports basic python types now.

**Comment by sekwiatkowski** [comment]
Wow, this keeps getting better and better. I will try out the Python types.

**Comment by sekwiatkowski** [comment]
One more question: can I use $expr$ as the default value?

I'm trying to get this template to work:
```
.eifc: else if condition
       ANY →  elif $CONDITION:expr$:\
                 $END$
````
Using two colons (`$CONDITION::expr$`) and removing `$END$` or `elif` yields the same result. The expression is not set as the default value.

**Comment by xylo** [comment]
Sorry, but it looks like using `expr` as a default value is not supported by `com.intellij.codeInsight.template.postfix.templates.StringBasedPostfixTemplate`.
