### ISSUE TITLE
Using defined Variable again

### ISSUE THREAD

**Issue by berk-can** [xylo/intellij-postfix-templates#126]
When I create a variable lets say it is $VAR0$ and then I reuse that $VAR0$ it doesnt work

logical example for this feature is:

```
for int $VAR0$ =0; $VAR0$<$expr$ ; $VAR0$++{\
   $END$\
}
```

is there a way to achieve this ?

**Comment by xylo** [comment]
First of all, in which language do you want to apply this template code?

I tried it in Scala and it did work (`$VAR0$` is expanded in all three positions).

What exactly does not work for you?

What version of IDEA are you using?

**Comment by xylo** [comment]
This is how my template looks like:

```
.test : test
    ANY  → for int $VAR0$ =0; $VAR0$<$expr$ ; $VAR0$++{\
       $END$\
    }
```

**Comment by berk-can** [comment]
I am writing Go in Goland, which Ide are you using?

**Comment by berk-can** [comment]
might be an issue with ide because of not reloading changes in config
I changed my config file and restarted Goland IDE and confirmed in settings that my changes are reflected but when I use postfix it is still generating old one

**Comment by berk-can** [comment]
I can confirm this is not an logic issue and it is related to IDE (Goland) I am using
I restarted my PC & opened IDE and it started working

Sorry for bothering :) Amazing plugin btw, thanks for it

**Comment by xylo** [comment]
Thanks.  I'm happy that it works for you now.  :)
