### ISSUE TITLE
suggestVariableName NOT working in Scala

### ISSUE THREAD

**Issue by cassiuscai** [xylo/intellij-postfix-templates#129]

**Comment by xylo** [comment]
That's nice. :)

**Comment by xylo** [comment]
Do you want me to do something with this ticket?

**Comment by cassiuscai** [comment]
Sorry type error? I mean NOT working

**Comment by xylo** [comment]
Ah, OK. :smiley:
Yes, `suggestVariableName` is a macro from Jetbrains and it only supports Java code as far as I know.  I'm not sure but there might also be a similar macro for Scala code.
