### ISSUE TITLE
plugin is not enabled by default (fresh install)

### ISSUE THREAD

**Issue by 1bytee** [xylo/intellij-postfix-templates#13]
... while it's marked as enabled in `Custom Postfix Templates`. After unchecking, `Apply` and checking again it stays enabled.

**Comment by 1bytee** [comment]
See: https://plugins.jetbrains.com/plugin/9862-custom-postfix-templates#comment=23658

**Comment by xylo** [comment]
Oh, good observation!  When I think about this "enable plugin" option I think it's actually useless since one can enable and disable plugins also in Settings->Plugins.  Thus I will remove the option and hopefully it fixes the problem.  Thanks for the tip, 1bytee!
