### ISSUE TITLE
No way to create custom templates in GoLand?

### ISSUE THREAD

**Issue by lilianaziolek** [xylo/intellij-postfix-templates#134]
I have just installed the plugin in latest version of GoLand (2019.2) and can't get the plugin to pick up my own template.
1. The menu "Edit templates of current language" does nothing (does not open any window)
2. Open Settings / Upgrade templates does open the config window, but I can't figure out a way to make any changes to templates. I tried adding both user and local template, and none of them shows any content in the window. The right-hand area is also not editable (not sure if it should be). For the local file (placed in my project) I have edited the contents in GoLand editor but this content does not seem to be picked up in the Custom Postfix Templates window. (as per screenshot)

Is this perhaps some sort of incompatibility with GoLand 2019.2 ? Am I doing something wrong? From your docs it seems like there should be a way to add own definitions but the only thing I managed to get to work is the ones from other repos (e.g. Go's postfixes from philipgriggs repo work fine)
![image](https://user-images.githubusercontent.com/271914/63362589-60d87f80-c372-11e9-8f54-abd86895e455.png)

Any help appreciated!

P.S. I also tried closing and re-opening GoLand and this still does not help in bringing the contents of the local file into config window.

**Comment by xylo** [comment]
To 1.) Hm, for me it works. Before you click on "Edit templates of current language" you have to open a Go file in the editor. The current language is determined by the currently active editor tab.
Afterwards you should normally see a popup like this:
![image](https://user-images.githubusercontent.com/577869/63378325-4b734d80-c392-11e9-8170-abad67c3cc51.png)
If this does not work, maybe it's an OS specific issue.  Which OS are you using?

To 2.) The settings dialog window is just for managing the template files.  You can create new files there but you cannot edit them there.  The reason for that is that the embedded editors in dialog windows are not comparable to the editor tabs in IDEA.  The embedded editors mainly only support syntax highlighting but do not support code completion and other features.

To 3.) The handling of the "local template files" is probably not very intuitive, I have to admit.  Although one would think that they are directly included they are actually handled like external web templates, which means that the plugin creates a local copy of them whenever an update is performed.  So "Update now" should also update the content of the local template files (but you might have to reopen the settings dialog after the update).

OK, I see that the plugin could be more intuitive and I want to improve that.  So thanks for your message.  It gave me already some very useful hints.  If you have more suggestions please let me now.

**Comment by lilianaziolek** [comment]
Aaaah, I see, yes, thanks! After opening Go file the menu has opened the extra user file , I could edit it and now the template contents shows up in the config windows.
The local file doesn't seem to propagate correctly even after I clicked "Update now" and closed and opened the settings dialog... BUT, as the other route seems to work, I don't mind as I think this will be enough :)
Thanks for a quick answer, and if that was helpful in any way I'm glad. Thanks for creating the plugin!

**Comment by xylo** [comment]
Thanks.  I've created a new issue (#136) to make the plugin more intuitive.  So I will close this one now.
