### ISSUE TITLE
Is it possible to have multiple $expr$ as stated below?

### ISSUE THREAD

**Issue by xylo** [xylo/intellij-postfix-templates#137]
hi @xylo is it possible to have multiple $expr$ as stated below ? 
i want to transform the 3 values into specific format to declare as element. thanks
![image](https://user-images.githubusercontent.com/1736817/63408912-46f27780-c41a-11e9-99bb-4a60482372c3.png)

_Originally posted by @ganjarpanji in https://github.com/xylo/intellij-postfix-templates/issues/29#issuecomment-523321785_

**Comment by xylo** [comment]
I'm not completely sure what you want to do.  Do you want to have a postfix template called `elementName` that takes the prefix (in this case `a.b` and splits it so that `a` and `b` can be used as different `$expr$` variables?

**Comment by ganjarpanji** [comment]
yes, so whenever i have a pattern `string.string.string` it could have autocomplete to generate as in the picture, and the last string will used as the variable name(elementName).

**Comment by xylo** [comment]
As far as I know this is not how the postfix completion of IDEA works.  Postfix templates can only be applied on valid expressions and in your example it looks like `a`, `b`, and `elementName` are not declared at all, i.e. they are neither variables, methods, etc and therefore no valid expression.

I think what you are looking for are live templates: https://www.jetbrains.com/help/pycharm/tutorial-creating-and-applying-live-templates-code-snippets.html

**Comment by xylo** [comment]
I mean postix templates can also make use of different variables but the concept is different from live templates.  Postfix templates require an expression to work with while live templates do not.

**Comment by ganjarpanji** [comment]
thanks, will check into it. :)
