### ISSUE TITLE
use regularExpression Expression with $ in Pattern failed

### ISSUE THREAD

**Issue by zhyon404** [xylo/intellij-postfix-templates#138]
I want to want a expression return err and default value in go. something like
```
.rw : return wrapped err
    ERROR  → if $expr$ != nil {\
		return $RETURN:regularExpression(defaultReturnValues, "([^,]*$)", "")$errors.Wrap($expr$, "")$END$\
	}\
```
```"([^,]*$)" ```conflicted with ```$``` in variable. Any suggestion on how to do it?

**Comment by xylo** [comment]
It's supposed to work if you escape the inner `$` with `\`.  But somehow it doesn't.  I created bug #139 for that purpose.

**Comment by xylo** [comment]
I think your template should work now with version 2.10.7.

**Comment by xylo** [comment]
However, I guess you have to escape the $ within the variable. I don't know if other characters have to be escaped as well.

**Comment by zhyon404** [comment]
it worked. thanks

**Comment by xylo** [comment]
:) Thanks for the feedback.
