### ISSUE TITLE
Replace org.reflections.Reflections by a simple implementation

### ISSUE THREAD

**Issue by xylo** [xylo/intellij-postfix-templates#150]
org.reflections.Reflections seemingly causes problems with Oracle JRE 11 and needs to be replaced.

**Comment by olivergondza** [comment]
It appears to be used to locate all implementations of certain class, witch is not quire straightforward (with java reflections). Maybe there is something that has changed either in JDK or IDEA classpath that prevent the classpath scanning to work as intended.

I am wondering if https://github.com/jenkinsci/lib-annotation-indexer or plain old hardcoded list of provided implementation would not work here (provided they are all part of this project).

**Comment by xylo** [comment]
Fixed in 2.10.13.
