### ISSUE TITLE
2020.1 EAP

### ISSUE THREAD

**Issue by enerjazzer** [xylo/intellij-postfix-templates#152]
Could you please release a version which is compatible with the current EAP?

**Comment by xylo** [comment]
Building the plugin fails at the moment.  ([issue discussion](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007541279-Plugin-building-fails-for-IDEA-2020-1-EAP-plugin-requires-com-intellij-modules-python-core-capable-plugin-))

**Comment by xylo** [comment]
Waiting for https://youtrack.jetbrains.com/issue/IDEA-233016 to be fixed.

**Comment by ikhoon** [comment]
@xylo The issue seems to be fixed by this commit https://github.com/JetBrains/intellij-community/commit/2a8d96643fe7310728c30d3d38565837bd637e10
Thanks for making and maintaining this awesome plugin. 🙏

**Comment by xylo** [comment]
Thanks for the hint.  I just tested the plugin build process with the new EAP release.  Unfortunately, the build still fails, but I get another exception.  Have to look into this...

**Comment by xylo** [comment]
I created a new bug report for the new issue: https://youtrack.jetbrains.com/issue/SCL-17211

I will also try to work around the while buildSearchableOptions task.

**Comment by xylo** [comment]
OK, skipping a task is very easy with gradle.  So I skipped it and published an EAP version for IDEA 2020.1 EAP.
