### ISSUE TITLE
Plugin not working in Android Studio 3.6(AI-192.7142.36.36.6200805)

### ISSUE THREAD

**Issue by AndyWing** [xylo/intellij-postfix-templates#156]
I was able to use CPT in version Android Studio 3.5, but after upgrading to Android Studio3.6
It shows nothing when i tap .

I found a solution to this problem in [https://github.com/xylo/intellij-postfix-templates/issues/147](https://github.com/xylo/intellij-postfix-templates/issues/147)

But i cannot install the version. 2.10.14.193, it limit the version Build #193.
But, Android Studio 3.6 is based on Build #AI-192.7142.36.36.6200805.

Is there any way I can solve this problem?

Thanks.

Android Studio 3.6
Build #AI-192.7142.36.36.6200805, built on February 12, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

CPT version : 2.10.10.192

**Comment by xylo** [comment]
Fixed in version 2.14.192.

**Comment by AndyWing** [comment]
Thank you very much. 
Developing without CPT is not as comfortable as before.

**Comment by xylo** [comment]
@AndyWing Do you have some Android templates that might be also useful for the community?

**Comment by Alexqwesa** [comment]
postfix-templates doesn't work in:

Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 27, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.3.18-59.34-default
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Registry: ide.instant.shutdown=false, external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: HighlightBracketPair, IdeaVIM, Key Promoter X, com.andrey4623.rainbowcsv, com.ankit.mahadik.json.dart.class, com.cjamcu.getx-snippets, com.gionchat, com.herbert.george.flutter-snippets, com.tao.bloc, Dart, andrasferenczi.dart-data-plugin, com.ixigua.flutter_asset_iteral, some.awesome, org.jetbrains.kotlin, io.flutter, cn.te0.flutter-getx-starter, de.mariushoefler.flutter_enhancement_suite, com.developerphil.adbidea, com.chrisrm.idea.MaterialThemeUI, io.nimbly.json.Any2Json, izhangzhihao.rainbow.brackets, org.intellij.plugins.markdown
Current Desktop: KDE

**Comment by xylo** [comment]
@Alexqwesa I created a new ticket for this issue: #209
