### ISSUE TITLE
Add full type support for kotlin language

### ISSUE THREAD

**Issue by MaaxGr** [xylo/intellij-postfix-templates#158]
Currently it's only possible to create postfix templates for "Any"-Datatype. Is there a plan to support other types also?

**Comment by xylo** [comment]
I already tried to add a full type support for Kotlin. Unfortunately, it's very hard to get to the necessary information. I once asked for them in the IDEA dev forum but didn't get a full answer: https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000728144

So I stopped further investigations. Kotlin does not seem well supported by IDEA although it's the language of JetBrains. That's weired.

**Comment by xylo** [comment]
Duplictae of #29.

**Comment by MaaxGr** [comment]
I think i found the missing part in the puzzle! We need a DescriptorRenderer to convert the KotlinType instance with the simple name to the fqdn. I have opened a pull request for my solution. Feel free to change something, if it don't matches code guidelines or my method is in the wrong class.

**Comment by xylo** [comment]
Thanks a lot, @MaaxGr. :) Nice work.
