### ISSUE TITLE
It seems it isn't possible to use some of mapping types

### ISSUE THREAD

**Issue by m-titov** [xylo/intellij-postfix-templates#16]
Subj. 
Please see example here:
![image](https://user-images.githubusercontent.com/25036750/28753735-85444ed4-7541-11e7-8728-bb2ffd3aae37.png)

It warns that: 
> Class not found
> CptTokenType.MAP expected, got '_'

The same for NOT_PRIMITIVE and ITERABLE_OR_ARRAY,

**Comment by xylo** [comment]
Thanks for reporting the bug.  I forgot to add the underscore to the valid tokens.  I fixed it in version 0.9.3 (0420417db322b57f975efff8951afd762e37c111) which is hopefully coming at the beginning of next week.
