### ISSUE TITLE
[bug] soutv error 

### ISSUE THREAD

**Issue by geekyouth** [xylo/intellij-postfix-templates#162]
The java and scala templates are not recognized
Print format error

![image](https://user-images.githubusercontent.com/12899262/79299612-1ca87980-7f17-11ea-8bc6-31db3939afaa.png)

![image](https://user-images.githubusercontent.com/12899262/79299643-31850d00-7f17-11ea-8081-5f689e689c3d.png)

**Comment by xylo** [comment]
Thanks for the hint.  I fixed the bug that the quotes were not escaped.  You can force update your templates by going to File->Settings->Editor->Custom Postfix Templates and then pressing on "Update Now".
