### ISSUE TITLE
the plugin  could not add my own template file in local system

### ISSUE THREAD

**Issue by OToNaShi-4** [xylo/intellij-postfix-templates#168]
after add the file in plugin setting and updated ,it show nothing in read-only editor
![微信图片_20200617114428](https://user-images.githubusercontent.com/48279252/84852646-f7a7c280-b08f-11ea-9689-1bc216c37431.png)

**Comment by xylo** [comment]
Indeed. Can confirm the behavior. Local template files do not work anymore. :(
I'll try to look into this within the next days.

**Comment by schrek1** [comment]
stilll pending :/

**Comment by xylo** [comment]
An updated version of this bug report is under #220.  Therefore I'm closing this issue as duplicate now.

Duplicate: #220
