### ISSUE TITLE
Need IDE version 203.* support.

### ISSUE THREAD

**Issue by jwiede** [xylo/intellij-postfix-templates#177]
In order to support recent EAPs, need plugin suipport updated for IDE version 203.*.

**Comment by ikopysov** [comment]
I plan to work on this.
Please, let me know if you are already implementing it.

**Comment by xylo** [comment]
Damn.  Looks like I lost your pull request. :(
Do you still have a local copy of your changes?

**Comment by xylo** [comment]
OK, found it: https://github.com/ikopysov/intellij-postfix-templates/tree/issue-177.

I will merge it in some hours and create a new release for IDEA 2020.3 EAP.

**Comment by xylo** [comment]
@ikopysov Thanks a lot for your contributions. (I did not have much time in the last months to work on the plugin)
