### ISSUE TITLE
add some kotlin template

### ISSUE THREAD

**Issue by Jian-Min-Huang** [xylo/intellij-postfix-templates#183]
Hi, I'd like to share some kotlin postfixTemplate with unit test related (junit5, assertj, mockito).

Our team used to use Java with this plugin, It's really awesome. 👍
Saving out times and make our coding professional. 😎

Can I just send a Pull Request for you ?

**Comment by xylo** [comment]
Yeah. You can send me a pull request.

Would be great to have some useful Kotlin templates.

**Comment by Jian-Min-Huang** [comment]
Hi, @xylo  I have one little question 🙋‍♂️
When will my pr release 😄

My friends still use import web template from GitHub my repo or your repo.
It's a little inconvenience, haha

**Comment by xylo** [comment]
Oh.  I forgot that the templates need to be located in the master branch.  I'll fix this...

**Comment by xylo** [comment]
OK. The problem was that the Kotlin template files have not been referenced in `webTemplateFiles.yaml`.  That's fixed now.
