### ISSUE TITLE
Hope to make a set of VScode plug-in of Java-postfix-templates

### ISSUE THREAD

**Issue by zmwxiaoming** [xylo/intellij-postfix-templates#187]
Hope to make a set of VScode plug-in

![image](https://user-images.githubusercontent.com/8034998/101116195-982e7680-361f-11eb-9640-a56aba760a25.png)

**Comment by xylo** [comment]
Please use English in this project.

**Comment by xylo** [comment]
I'm not sure what this ticket is about.

**Comment by xylo** [comment]
The integration of this plugin in VScode is not possible as far as I know.  VScode is not using the IDEA platform for coding.
