### ISSUE TITLE
无法使用、保存设置

### ISSUE THREAD

**Issue by ljynfo** [xylo/intellij-postfix-templates#188]
下载插件安装后，设置里面的Custom Postfix Template里面是空的，在github上下载模板文件到本地以本地文件倒入后保存设置，再次打开也是空的
idea:2020.3

**Comment by xylo** [comment]
Please use English on tickets and contributions.

**Comment by ljynfo** [comment]
After installing the plugin, the Custom Postfix Template in the Settings is empty. Download the Template file locally on Github to save the Settings after loading the local file, and open it again is empty

Idea: 2020.3

**Comment by xylo** [comment]
There is currently indeed a problem with using local template files (issue #168).

However, the automatic download of the web templates is expected to work.  Can you go to the IDEA settings -> Editor -> Custom Postfix Templates and make a screenshot of the window?  I wonder what went wrong there.  Did you get any exception?

**Comment by ljynfo** [comment]
[](url)

**Comment by ljynfo** [comment]
[``](url
![QQ截图20201215194128](https://user-images.githubusercontent.com/42232422/102210875-b80e4600-3f0d-11eb-9087-15bea20a01a4.png)
)

**Comment by ljynfo** [comment]
This picture is my Settings page. The template is empty after I download and install the plug-in.
Manually adding the local template also does not save properly, so I cannot use this plugin

**Comment by xylo** [comment]
Can you give me more information about your OS and IDEA version?

You can find the idea version under Help -> About.  You can find a small copy icon there:
![grafik](https://user-images.githubusercontent.com/577869/102215412-f984fe00-3ed9-11eb-9f48-dabf0b5375fc.png)

**Comment by ljynfo** [comment]
![微信图片_20201216131611](https://user-images.githubusercontent.com/42232422/102308128-f143c600-3fa0-11eb-94d6-6ce48248514b.png)

This is my OS and IDEA version, thanks,
The template files of web appear after I change my hosts,
I am not sure which domain name can't resolve THE IP, but it is ok for me to add this, please tell me which domain name affects it
`# GitHub Start 
192.30.253.112    Build software better, together 
192.30.253.119    gist.github.com
151.101.184.133    assets-cdn.github.com
151.101.184.133    raw.githubusercontent.com
151.101.184.133    gist.githubusercontent.com
151.101.184.133    cloud.githubusercontent.com
151.101.184.133    camo.githubusercontent.com
151.101.184.133    avatars0.githubusercontent.com
151.101.184.133    avatars1.githubusercontent.com
151.101.184.133    avatars2.githubusercontent.com
151.101.184.133    avatars3.githubusercontent.com
151.101.184.133    avatars4.githubusercontent.com
151.101.184.133    avatars5.githubusercontent.com
151.101.184.133    avatars6.githubusercontent.com
151.101.184.133    avatars7.githubusercontent.com
151.101.184.133    avatars8.githubusercontent.com

 # GitHub End`

**Comment by ljynfo** [comment]
I am very sorry, my English is poor. Thanks for your help.
I have found a template that is suitable for me, but I cannot add it into the plug-in for use. I really hope to use this template, thank you for your help

**Comment by xylo** [comment]
The plugin loads content/templates from https://raw.githubusercontent.com/...
e.g. https://raw.githubusercontent.com/xylo/intellij-postfix-templates/master/templates/webTemplateFiles.yaml

More hostnames are not needed for the plugin.

To add your own templates, first navigate to a source file of the programming language you want to add templates for.  Then press shift+alt+P or go to Tools->"Custom Postfix Templates"->"Edit Templates of Current Language" and select "Create new user template file" and start writing your own templates.

**Comment by xylo** [comment]
I close this issue since it was only related to personal firewall/dns settings.
