### ISSUE TITLE
Kotlin cannot reach the second rule

### ISSUE THREAD

**Issue by pdog18** [xylo/intellij-postfix-templates#189]
.ts : timber string
    STRING_LITERAL  → Timber.d($expr$)
    ANY → Timber.d("$expr$ = %s",$expr$$END$)
    
    
——————
Expect：
“a”.ts  → Timber.d("a")
a.ts  → Timber.d("a = %s", a)
——————
Actually：
“a”.ts → Timber.d("a")
a.ts → Timber.d(a)

————The second rule can't reached——————
 ANY → Timber.d("$expr$ = %s",$expr$$END$)

**Comment by xylo** [comment]
Indeed.  STRING_LITERAL is not working as expected anymore.

**Comment by pdog18** [comment]
> Indeed. STRING_LITERAL is not working as expected anymore.

Is Kotlin only have ANY now？

**Comment by xylo** [comment]
I just tested INT_LITERAL and it has the same problem.  They all match all expressions.  So yes, the Kotlin support is back to untyped templates only. :(

**Comment by pdog18** [comment]
Thanks, I hate Kotlin.
