### ISSUE TITLE
Rust templates not applicable on nested expressions

### ISSUE THREAD

**Issue by whatisaphone** [xylo/intellij-postfix-templates#191]
I'm using this plugin in CLion with Rust. It works great, but only some of the time. Some types of expressions don't seem to work.

Example, these work great (i.e., if you go to the end of the expression, and type a period, my templates show up in autocomplete and I can use one by pressing tab)

```rust
fn main() {
    foo()
    Foo {}
}
```

However these don't work (my templates do not show up in autocomplete):

```rust
fn main() {
    foo(bar)
    foo()?
    Foo { bar }
    Foo { bar: bar }
    dbg!(foo)
}
```

**Comment by xylo** [comment]
This bug is fixed in the latest version (IDEA 2021.2 EAP and Custom Postfix Templates 2.12.1.212).
