### ISSUE TITLE
Please support IntelliJ IDEA 2021.1 (IU-211.*)

### ISSUE THREAD

**Issue by dashiyou** [xylo/intellij-postfix-templates#192]
As Custom Postfix Templates requires build 203.*, it cannot be used in IntelliJ 2021.1 (EAP)

Message from Event Log:

Plugin 'Custom Postfix Templates' (version '2.12.0.203') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IU-211.6085.26

**Comment by xylo** [comment]
Fixed with version 2.12.0.211.
