### ISSUE TITLE
How to make postfix templates suggestion appear in all contexts?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [xylo/intellij-postfix-templates#197]
I'm using custom Rust postfix templates. When I use it against simple expressions, like `"value".my_postfix_template`, it works well. However, when the expression is more complex, like `io::stdin().read_line(&mut guess)`, it doesn't show in the popup list when I use `io::stdin().read_line(&mut guess).my_postfix_template`. How can I make the postfix template suggestion always show up in the popup suggestion?

**Comment by xylo** [comment]
This bug is fixed in the latest version (IDEA 2021.2 EAP and Custom Postfix Templates 2.12.1.212).
