### ISSUE TITLE
Please add support IDEA 2022.1 EAP

### ISSUE THREAD

**Issue by dashiyou** [xylo/intellij-postfix-templates#212]
Please add support IDEA 2022.1 EAP .Thanks

**Comment by haocheng** [comment]
Hi,

Any updates on this issue since 2022.1 is already released? 
Thank you! 🙏

**Comment by xylo** [comment]
I tried to port the plugin to IDEA 2022.1 some weeks ago, but I came across a JetBrains problem (https://youtrack.jetbrains.com/issue/IDEA-287547) and could not test the plugin in IDEA anymore.  I'll test it now with the new IDEA build.  Hope it got fixed in the meanwhile.

**Comment by xylo** [comment]
After updating IDEA to 221.5080.210, the error above disappear and the error https://youtrack.jetbrains.com/issue/IDEA-291192 appeared. :D
Anyway, that's fixed now, too.  So I'll try to build the release.

**Comment by xylo** [comment]
OK, the plugin is finally available for IDEA 2022.1.
