### ISSUE TITLE
Apply to function

### ISSUE THREAD

**Issue by goto1134** [xylo/intellij-postfix-templates#22]
I'd like to use the tool to refactor method. For example, annotate with custom annotation with a value taken from method. Is there a way to do it?

**Comment by xylo** [comment]
I'm not sure what you mean.  Can you give me an example?

**Comment by xylo** [comment]
@goto1134 The current implementation of postfix templates can only influence the expression right before the template name.

If you have code like
```
public void test() {
    "1".myTemplateName
}
```
the template expansion of `.myTemplateName` can only effect `"1"`.  So the template is unable to add annotations to the method.

Have you tried to use live templates for your purpose?

**Comment by goto1134** [comment]
@xylo I found the solution for my problem in another IDEA tool, called `Structural search and replacement`.

**Comment by xylo** [comment]
@goto1134 Thanks for the hint.  I didn't know that plugin yet.  It looks pretty awesome.
