### ISSUE TITLE
Postfix Suggestion not showing up in 2022.3

### ISSUE THREAD

**Issue by mlizzi** [xylo/intellij-postfix-templates#229]
I'm not sure exactly what's going wrong. When I add this plugin to a new install, it works fine. Whenever I make settings changes, it eventually stops working. Is there a setting I should be leaving on, or a shortcut that I need to have / enable to get this working again?

**Comment by xylo** [comment]
Can you send me a screenshot of your plugin settings?

I wonder if the tree with the template files gets correctly loaded.

**Comment by mlizzi** [comment]
![image](https://user-images.githubusercontent.com/25866465/212433923-86492bcd-d53f-49b0-846c-ee1413323816.png)

I'm not sure if other pycharm settings are conflicting with getting this working?

**Comment by xylo** [comment]
Your settings look good.  That's strange.  So the problem appears in PyCharm.  Going to reproduce the bug...

**Comment by xylo** [comment]
I just tested PyCharm with the plugin and it worked for me.  Which settings did you change when the plugin stopped working?
The settings shown your screenshot look just normal.  I have the same settings right now and the plugin works for me.

**Comment by mlizzi** [comment]
I just reinstalled a fresh copy of pycharm and got it working again. No clue how I got into that mess, but seems to be fine for now!
