### ISSUE TITLE
Short is not recognized by NUMBER matcher

### ISSUE THREAD

**Issue by 1bytee** [xylo/intellij-postfix-templates#23]
Every primitive type except `short` is being recognized.

![image](https://user-images.githubusercontent.com/18426655/29239407-4522526c-7f4e-11e7-81e6-e07db4e0d4a1.png)

![image](https://user-images.githubusercontent.com/18426655/29239409-554183e8-7f4e-11e7-8dfa-54152ba880a5.png)

**Comment by xylo** [comment]
Thanks for the hint.  I also forgot to add a `.toShort` template.
