### ISSUE TITLE
How to use template variables's `skip if defined' attribute?

### ISSUE THREAD

**Issue by stop-bullshit** [xylo/intellij-postfix-templates#230]
Does the plugin's template syntax support the skip if defined attribute? 
If not used, I need to press Enter again after code completion
![image](https://user-images.githubusercontent.com/25337521/212373190-fff6c35b-dc5a-4b30-83bc-0dee86d3eea7.png)

such as :
![image](https://user-images.githubusercontent.com/25337521/212373456-37369578-80c2-46e5-a702-bc424c49c6cc.png)

expect:
![image](https://user-images.githubusercontent.com/25337521/212373607-ff330863-3159-40d2-8681-ae7a11da404c.png)

**Comment by xylo** [comment]
I guess that 'Skip if defined' skips the input of this variable if the variable expression is defined.
The plugin provides a similar function allowing you to skip variables marked with an asterisk (`*`) behind the variable name.  However, those variables are always skipped.

In your case the template would look like this:
```
.log : log
	ANY  →  console.log($LINE*:lineNumber():""$, $END$)
```

More information about writing templates can be found here: https://github.com/xylo/intellij-postfix-templates#template_code

**Comment by stop-bullshit** [comment]
OK ,thanks for your apply.
