### ISSUE TITLE
how import static class automate ?

### ISSUE THREAD

**Issue by StackTc** [xylo/intellij-postfix-templates#237]
.newlist : new Object ArrayList
    ANY →  List<$expr$> $end$ = new ArrayList<>();
    
  this is my custom template , I will use like Animal.newlist. and now it will not import the class automate. but I find in idea postfix completion, there is a setting "use static import if possible", it works .
  and how works in the custom-postfix-templates plugin ?

**Comment by xylo** [comment]
Just add "[USE_STATIC_IMPORTS]" to your rule, e.g.:

```
.ls : create LazySeq
	ANY [de.endrullis.lazyseq.LazySeq]  →  [USE_STATIC_IMPORTS] iat.utils.javaScala.StaticImports.ls($expr$)
```
