### ISSUE TITLE
是否可以本地初始化激活呢？（优化建议）

### ISSUE THREAD

**Issue by Stiles-Wangs** [xylo/intellij-postfix-templates#240]
如果本地初始化激活就好了。
模板根据需求在设置中手动去拉取更好。
好处：
用户决定是否使用通用模板，还是根据实际情况。个性化配置。减少不必要的网络请求
从而使用户不会因为网络问题而无法使用此插件。特别是那种内网用户。通过安装包来使用插件。导致无法使用此插件

**Comment by xylo** [comment]
Sorry, but the project language is English.

**Comment by cassiuscai** [comment]
> 如果本地初始化激活就好了。 模板根据需求在设置中手动去拉取更好。 好处： 用户决定是否使用通用模板，还是根据实际情况。个性化配置。减少不必要的网络请求 从而使用户不会因为网络问题而无法使用此插件。特别是那种内网用户。通过安装包来使用插件。导致无法使用此插件

这些功能已经支持，可以在设置页面进行设置和勾选是否启动这些模板，也可以全局设置是否启用自动更新。

These features are already supported. You can configure and select whether to enable these templates on the settings page. Additionally, you can globally set whether to enable automatic updates.

**Comment by xylo** [comment]
@cassiuscai Thanks for the clearification. 👍
