### ISSUE TITLE
TEMPLATE_CODE: NO (optional) not working in Kotlin

### ISSUE THREAD

**Issue by dyguests** [xylo/intellij-postfix-templates#242]
Hello~

Here is my code:

```
.byVal : val name by name:MutableState
    ANY →  val $name#2::name$ by $expr$.$name#1::name$

# Another try
.byVal : val name by name:MutableState
    ANY →  val $name#2::name$ by $expr$.$name#1::name$
```

I want set the cursor at `name#1` first.
But actually is at `name#2`.

![image](https://github.com/xylo/intellij-postfix-templates/assets/7933189/25900148-5a6d-4488-9128-7901283e9a8d)
![image](https://github.com/xylo/intellij-postfix-templates/assets/7933189/52f529f3-e72c-4011-a964-133518b762a3)

**Comment by dyguests** [comment]
I got it.

It seem `NO (optional)` not working on the same name `$name$`.
But it's useful for code auto completion.

Can you add this feature in furture?

**Comment by xylo** [comment]
Unfortunately, this is not possible with the Postix Template API that IDEA provides:
https://github.com/JetBrains/intellij-community/blob/74b924e0526a169269e54a24cf01b42124aae0a3/platform/analysis-impl/src/com/intellij/codeInsight/template/Template.java#L51

I can tell IDEA only that different variable names contained in the template and I define the order in which the variable shall be visited.  But a variable $name$ with multiple occurrences in the template is still only one variable.  How the different occurrences of one variable are handled is managed internally in IDEA.  Sorry.
