### ISSUE TITLE
Add Scala support

### ISSUE THREAD

**Issue by xylo** [xylo/intellij-postfix-templates#28]
At the moment adding Scala support is not really trivial, since the Scala plugin of IDEA is not yet written in Scala 2.12.  Thus it is not compatible with Java 8 and several important functions are not callable from Java 8 code.  So we either have to wait for the Scala plugin to get upgraded to Scala 2.12 or we have to write a "wrapper" in Scala 2.10 which calls the functions of the Scala plugin that we need and provides a Java 8 compatible interface for those (using simple types and interfaces) and then call those functions from our Java 8 code.

I would rather suggest to wait for the Scala plugin to get upgraded than doing a temporary and costly hack.  So let's wait, I would say.

**Comment by aristotll** [comment]
Intellij 2017.3 scala uses Scala 2.12, see https://github.com/JetBrains/intellij-scala/blob/eb0f5dba8b0bdf225077ca5aba260f0d08f387e8/project/dependencies.scala#L4

**Comment by xylo** [comment]
That are great news. Thanks a lot!

**Comment by xylo** [comment]
Added basic support for Scala (untyped templates only).
