### ISSUE TITLE
Add full Kotlin support

### ISSUE THREAD

**Issue by xylo** [xylo/intellij-postfix-templates#29]

**Comment by m-titov** [comment]
+1

**Comment by xylo** [comment]
Working on it...

**Comment by xylo** [comment]
OK, a very basic support for Kotlin templates has been added.  At the moment one cannot assign templates to certain types (e.g. boolean, certain classes, ...).  The matching type has to be `ANY` for now.

**Comment by m-titov** [comment]
cool. Thanks a lot

**Comment by xylo** [comment]
Thanks to Dmitry Jemerov (https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000728144) I should be able to detect the type of the Kotlin expression.

**Comment by pdog18** [comment]
It's so comfortable, Want to support `STRING_LITERAL`         
：）

**Comment by xylo** [comment]
Sorry, but in the near future I won't find the time to extend the Kotlin support to more than the ANY type.  Maybe someone else can help here.

**Comment by ganjarpanji** [comment]
is it possible to create template that will reflect multiple lines?

**Comment by xylo** [comment]
Oh, that's indeed an undocumented feature.  You can use multiple lines in a template by putting `\` at the end of the lines.

**Comment by xylo** [comment]
OK, I added a multi-line example to https://github.com/xylo/intellij-postfix-templates/blob/master/README.md#template-examples

**Comment by ganjarpanji** [comment]
hi @xylo is it possible to have multiple $expr$ as stated below ? 
i want to transform the 3 values into specific format to declare as element. thanks
![image](https://user-images.githubusercontent.com/1736817/63408912-46f27780-c41a-11e9-99bb-4a60482372c3.png)

**Comment by xylo** [comment]
@ganjarpanji I created a new thread for discussing your question, since this ticket is actually about adding full Kotlin support.

**Comment by xylo** [comment]
Duplicate of #158.
