### ISSUE TITLE
Support PHP and PhpStorm

### ISSUE THREAD

**Issue by tomasfejfar** [xylo/intellij-postfix-templates#35]
There has been a feature request for PhpStorm as well (https://youtrack.jetbrains.com/issue/WI-27660). But your plugin does not seem to be PhpStorm-compatible. 

Do you think it's possible to port this plugin to PhpStorm, please?

**Comment by xylo** [comment]
I guess it's possible to add support for PHP and PHPStorm, but at the moment I don't have the time for that.  But any pull requests are welcome.

**Comment by xylo** [comment]
Untyped PHP support added in version 2.3.0.
Compatibility with PHPStorm added in version 2.3.1.

**Comment by xylo** [comment]
Typed PHP support added in version 2.5.0.

**Comment by alozytskyi** [comment]
Does it work, I wonder? Doesn't seem to be work in PhpStorm 2019.1
