### ISSUE TITLE
Add template examples with macros to the README

### ISSUE THREAD

**Issue by xylo** [xylo/intellij-postfix-templates#40]

**Comment by DanChaltiel** [comment]
I created a live template as following : 
`android.util.Log.d("$USER$", "$CLASS_NAME$ :: $METHOD_NAME$ ($LINE_NUMBER$): $content$="+$content$);`

Variables are linked to macros as : 
- `USER=user(),default = MyTag, skip=true`
- `CLASS_NAME=className(), skip=true`
- `METHOD_NAME=methodName(), skip=true`
- `LINE_NUMBER=lineNumber(), skip=true`
- `content="", skip=false`

I want to create a postfix to use as object.logd : 
```
.logd : log la variable
	java.lang.Object         →  android.util.Log.d("MyTag", "$className$ :: $className()$ ($LINE_NUMBER$): $expr$="+$expr$);
```

Unfortunately, macros names aren't recognized.

What syntax should I use ?

**Comment by xylo** [comment]
Thanks for the macro names.  Your template code would be:
```
.logd : log la variable
	NON_VOID → android.util.Log.d("$user*:user():"MyTag"$", "$className*:className()$ :: $methodName*:methodName()$ ($lineNumber*:lineNumber()$): $expr$="+$expr$);
```

As described in https://github.com/xylo/intellij-postfix-templates#edit-the-templates the "*" behind the variable name means that the user interaction is skipped.  Moreover, macro names are placed behind the variable name separated by a ":" and the default value is placed behind the macro name, also separated by a ":".

**Comment by DanChaltiel** [comment]
Thank you very much !
I suggest you to add an example (this one or maybe an even more complete one) in your Readme.md, as I'm sure I couldn't find by myself just with the theoric explanations alone.

**Comment by xylo** [comment]
You're right.  There should be an example in the doc.  And I think your one is a pretty good one for this.

**Comment by xylo** [comment]
OK, I added two examples to the README which show how to use macros, variable reordering, variable reusage, default values, and interaction skipping.  So all functions should be covered now.
