### ISSUE TITLE
Add typed groovy support

### ISSUE THREAD

**Issue by aristotll** [xylo/intellij-postfix-templates#45]
Please add groovy support.
Something like https://github.com/xylo/intellij-postfix-templates/issues/28 and https://github.com/xylo/intellij-postfix-templates/issues/29

**Comment by xylo** [comment]
Hm, I just wanted to add support for Groovy, but unfortunately IDEA does not support postfix templates for Groovy yet.  So we have to wait for that before we can continue.

**Comment by xylo** [comment]
I made a mistake. Postfix templates work with Groovy as well.
So I added Groovy support in plugin version 2.4.0. 
So far it's only an untyped support.

**Comment by xylo** [comment]
Typed Groovy support was added in version 2.6.0.

**Comment by xylo** [comment]
BTW, if you like to share your postfix templates with the community, you're welcome.
