### ISSUE TITLE
can i  differentiate the ` java.lang.String `or `"string"`

### ISSUE THREAD

**Issue by pdog18** [xylo/intellij-postfix-templates#47]
this is my templates 
```
.timber : logcat with timber
	NON_VOID → Timber.d("$expr$ = %s",$expr$$END$);
```

if i have a String variable ，use the templates ,i  will get this 
```
String string = "String";
//string.timber
Timber.d("string = %s", string);
```
but if i hava a  character string ，i will get this
```
//"String".timber
Timber.d(""String" = %s", "String");
```

try change templates like this ,but not working for me 
```
.timber : logcat with timber
	java.lang.String → Timber.d($expr$,$expr$$END$);
	NON_VOID → Timber.d("$expr$ = %s",$expr$$END$);
```

can i can i  differentiate the ` java.lang.String `or `"string"`

**Comment by xylo** [comment]
At the moment you cannot.  I have to introduce a new type for this, e.g. STRING_LITERAL.
