### ISSUE TITLE
Cannot create postfix to wrap something in quotes

### ISSUE THREAD

**Issue by bo0tzz** [xylo/intellij-postfix-templates#54]
I often type a number value when a string is actually intended, and would like to be able to do something like `1.str` to get `"1"`. I tried to make a template for this but get the following error, and can't figure out how to fix it. https://i.imgur.com/Mx0CHZ0.png

**Comment by xylo** [comment]
You have to write:
```
.str : wrap in string
	NUMBER_LITERAL  →  "$expr$"
```

**Comment by bo0tzz** [comment]
Apologies, I'm dumb. Thanks!
