### ISSUE TITLE
Plugin gives NoClassDefFoundErrors with Scala or Kotlin plugin disabled

### ISSUE THREAD

**Issue by Janmm14** [xylo/intellij-postfix-templates#58]
https://gist.github.com/Janmm14/ed06d470c9776ad721673ccb06b9b550

Causes code completion to just work sporadically in most situations, postfix code completion completely not working and intellij's postfix completions settings not loading (in settings->editor->general)

**Comment by xylo** [comment]
Oh, that's not good.  Thanks for the bug report!

**Comment by xylo** [comment]
Hm, that's odd.  Actually IDEA is not supposed to load additional code completion tools for languages that are deactivated.  So I guess it's primarily a bug in the new IDEA 2018.1.  However, as long as IDEA behaves this way I have to fix it in CustomPostfixTemplates, too.

**Comment by Janmm14** [comment]
Causes code completion to just work sporadically in most situations, postfix code completion completely not working and intellij's postfix completions settings not loading (in settings->editor->general)

**Comment by xylo** [comment]
The new release 1.6.3 is available now.

**Comment by zxeoc** [comment]
Hi, I got a similar problem. When I try to use some postfix completion from IDEA itself (like ".var"), IDEA gives an error. This is the info:[https://gist.github.com/zxeoc/b833e170a907d55796fe5ddf15d9e8b9/](https://gist.github.com/zxeoc/b833e170a907d55796fe5ddf15d9e8b9/)

I'm using v2.0.7 and IDEA 2018.3 EAP.

**Comment by zxeoc** [comment]
I updated to 2.4.0 and it fixed now, thanks.

**Comment by xylo** [comment]
Thanks for the feedback. :)
