### ISSUE TITLE
IntelliJ IDEA 2018.1 Only the first one takes effect under the same rule

### ISSUE THREAD

**Issue by ma349432587** [xylo/intellij-postfix-templates#60]
Default properties I have never change
![image](https://user-images.githubusercontent.com/18508587/38672763-c3a82a24-3e81-11e8-8786-44d3ddd3e4cb.png)
ARRAY is fine
![image](https://user-images.githubusercontent.com/18508587/38672737-b11f4252-3e81-11e8-96bc-534c1b30b1b9.png)
java.util.Collection is not ok.
![image](https://user-images.githubusercontent.com/18508587/38672386-9ae5a9f0-3e80-11e8-8798-9e8a2f79ed46.png)
Then  I changed the order
![image](https://user-images.githubusercontent.com/18508587/38673074-be3130d0-3e82-11e8-9bc2-2089aa3239e0.png)
ARRAY 
![image](https://user-images.githubusercontent.com/18508587/38673278-71849c6c-3e83-11e8-8a34-52bd8e8ef64b.png)

**Comment by xylo** [comment]
Oh. I didn't notice this yet. Thanks for reporting.

**Comment by xylo** [comment]
Fixed in version 1.6.6.
