### ISSUE TITLE
Cannot install in AndroidStudio 2.2.3

### ISSUE THREAD

**Issue by johnwatsondev** [xylo/intellij-postfix-templates#61]
#### Problem
![jietu20180419-102827](https://user-images.githubusercontent.com/12760754/38968076-83d84fb0-43bc-11e8-9b61-29c5b480a59b.jpg)

I installed the jar in AndroidStudio2.2.3 and it give me this hint above.

Our plugin can be found in AndroidStudio 2.3.3/3.1.

#### Env
Android Studio 2.2.3
Build #AI-145.3537739, built on December 2, 2016
JRE: 1.8.0_112-release-b05 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by xylo** [comment]
Android Studio 2.2.3 is from 2016 and not supported anymore.  Please upgrade to Android Studio 3.1.1.  The plugin works only with newer versions of Android Studio.
