### ISSUE TITLE
a little doubt

### ISSUE THREAD

**Issue by sunrishe** [xylo/intellij-postfix-templates#79]
I tried to create a local template File, URL to fill in the `file://C:/intellij-postfix-templates/java/Test.postfixtemplates`, after saving, found in the preview box on the right and can't show the contents of the file, excuse me, what is this?

Here is a little suggestion, I hope to add a `Refresh` button on the toolbar of the Templates Files window, in order to manually refresh the local file or Web Templates file, because I found that the file posted on the web is not timely. Get not updated, even if you restart IDEA.

Thank you for browsing in your busy schedule.

**Comment by xylo** [comment]
Local template files now get updated whenever an IDEA project is opened.  So you usually do not have to press the "Update now" button for that.

So I think I solved all problems of this ticket, except the one that the content of a newly added local file is not immediately shown in the settings dialog.  However, this is a minor issue IMO.
