### ISSUE TITLE
After reinstall this plugin, can't work.

### ISSUE THREAD

**Issue by TYZRPVX** [xylo/intellij-postfix-templates#83]
I typed ".toLong" after a string, but no code generated as expected.  I have turned off the IntelliJ IDEA "Postfix Completion" ahead. 

Env like this

> IntelliJ IDEA 2018.1.6 (Community Edition)
> Build #IC-181.5540.7, built on July 11, 2018
> JRE: 1.8.0_144-b01 amd64
> JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
> Windows 10 10.0

**Comment by xylo** [comment]
Postfix completion must be enabled for this plugin (Settings->Editor->General->"Postfix Completion"->"Enable postfix completion" must be checked).

**Comment by TYZRPVX** [comment]
Do you mean this plugin has excluded default "Postfix Completion" templates like ".toLong", because this is duplicated.

**Comment by xylo** [comment]
By the way, you can also check if a template is defined via Custom Postfix Templates by pressing Alt+Enter in the completion popup.  If there is a third menu item like "Edit '.toLong' template" it's a template from CPT and you can select the option to see the template definition.

**Comment by TYZRPVX** [comment]
> As far as I know IDEA does not ship with a ".toLong" template, but it is part of the web templates file "xylo.numbers" which comes with Custom Postfix Templates.
> 
> Settings->Editor->General->"Postfix Completion" shows you all available postfix templates, i.e. those that ship with IDEA plus those that come with IDEA plugins (including this plugin).
> Try to select the ".toLong" template and you will probably see in the description that it's a "Combined postfix template." And in the "Before" and "After" field you probably read something with "Custom Postfix Templates".

![image](https://user-images.githubusercontent.com/7645818/46387833-61850a80-c6fb-11e8-8072-7580573123e8.png)

**Comment by xylo** [comment]
![grafik](https://user-images.githubusercontent.com/577869/46401329-e290d180-c6fc-11e8-9e90-8c2aee270557.png)
