### ISSUE TITLE
Can't find plugin in IntelliJ Plugin Repository

### ISSUE THREAD

**Issue by 1bytee** [xylo/intellij-postfix-templates#9]
Using: IntelliJ IDEA 2017.2 Build #IU-172.3317.76

**Comment by xylo** [comment]
@1bytee 
Yeah!  I'm also eager to see my plugin in the official repository.  I submitted it on Monday evening and it's now waiting for being approved by JetBrains.  They say normally the plugins is reviewed within two working days.  So it should probably get published today or at least in the next days.  If nothing happened until the end of the week I will ask JetBrains how long it will take.

**Comment by 1bytee** [comment]
Do you have like a preview build for me as a .jar? Or can you tell me how to build it myself ? 🔝

**Comment by xylo** [comment]
I wanted to say that it's pretty easy to compile the plugin and build the release, but when I tried it now on a different computer I recognized that I forgot to check in the project / module file that tells IDEA this is a plugin.  I filed a bug report for this: #10.

In the evening I can check it in.  But then I can also upload a jar file.

**Comment by 1bytee** [comment]
Ye just check it in. I'll try to build it then... Let's see :P

**Comment by xylo** [comment]
I checked it in.  Check it out, open it in IDEA and go to Build -> Prepare plugin module custom-postfix-template for deployment.  It generates a jar file that is located in the project directory.

**Comment by xylo** [comment]
It's available! :)

https://plugins.jetbrains.com/plugin/9862-custom-postfix-templates
