### ISSUE TITLE
Python template failed

### ISSUE THREAD

**Issue by blurhead** [xylo/intellij-postfix-templates#97]
.pr : print
    Any.pr  →  print($expr$)

.int : to int
    Any.int  →  int($expr$)

this is my python template for postfix completion. it does not work. 

I got error like this:
java.lang.IllegalStateException: @NotNull method de/endrullis/idea/postfixtemplates/languages/python/CustomPythonStringPostfixTemplate.getCondition must not return null

**Comment by gejun123456** [comment]
#98  i have fixed this.

**Comment by xylo** [comment]
Thanks a lot @gejun123456. I'll look through it...

**Comment by xylo** [comment]
I finally released version 2.8.2 fixing this issue.  Sorry that it took me so long.
